name: "Reviewers"
on:
  pull_request:
    types: [labeled, unlabeled, edited, synchronize, ready_for_review, locked, unlocked]
jobs:
  enforce:
    name: Enforce
    runs-on: ubuntu-latest
    steps:
    - uses: kobim/action-review-enforcer@v1
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
